# Generated by Django 6.0.4 on 2026-04-27 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("BTC", "Bitcoin (BTC)"),
                            ("ETH", "Ethereum (ETH)"),
                            ("USDT_TRC20", "USDT (TRC20)"),
                            ("USDT_ERC20", "USDT (ERC20)"),
                            ("USDT_BEP20", "USDT (BEP20)"),
                            ("USDC", "USD Coin (USDC)"),
                            ("BNB", "Binance Coin (BNB)"),
                            ("TRX", "TRON (TRX)"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("wallet_address", models.CharField(max_length=255)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                (
                    "network_label",
                    models.CharField(
                        blank=True, help_text="e.g. TRC20, ERC20", max_length=100
                    ),
                ),
                (
                    "minimum_deposit",
                    models.DecimalField(decimal_places=8, default=10, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Special deposit instructions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "payment_methods",
                "ordering": ["name"],
            },
        ),
    ]
