# Generated by Django 6.0.4 on 2026-04-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_seed_investment_plans"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_user_id_d685f3_idx",
            old_name="audit_user_action_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlog",
            new_name="audit_logs_created_262184_idx",
            old_name="audit_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="contactmessage",
            new_name="contact_mes_is_read_d3164f_idx",
            old_name="contact_is_read_idx",
        ),
        migrations.RenameIndex(
            model_name="contactmessage",
            new_name="contact_mes_email_a7fb56_idx",
            old_name="contact_email_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentplan",
            new_name="investment__is_acti_82f86b_idx",
            old_name="plan_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="investmentplan",
            new_name="investment__sort_or_bf52dd_idx",
            old_name="plan_sort_order_idx",
        ),
        migrations.AlterField(
            model_name="contactmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional extra details shown on plan card"
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="duration",
            field=models.CharField(
                help_text="e.g. '24 hrs', '7 Days', '30 Days'", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="interest",
            field=models.FloatField(help_text="Return percentage, e.g. 6 for 6%"),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="max_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave blank for Unlimited",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="investmentplan",
            name="sort_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Lower number displayed first on plan page"
            ),
        ),
    ]
