# Generated by Django 6.0.4 on 2026-04-27 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KYCProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_SUBMITTED", "Not Submitted"),
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="NOT_SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("full_legal_name", models.CharField(max_length=200)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("address", models.TextField()),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PASSPORT", "Passport"),
                            ("NATIONAL_ID", "National ID"),
                            ("DRIVERS_LICENSE", "Driver's License"),
                        ],
                        max_length=30,
                    ),
                ),
                ("document_number", models.CharField(max_length=100)),
                ("document_front", models.ImageField(upload_to="kyc_docs/front/")),
                (
                    "document_back",
                    models.ImageField(
                        blank=True, null=True, upload_to="kyc_docs/back/"
                    ),
                ),
                (
                    "selfie_with_doc",
                    models.ImageField(
                        blank=True, null=True, upload_to="kyc_docs/selfie/"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "kyc_profiles",
            },
        ),
    ]
