# Generated by Django 6.0.4 on 2026-05-07 10:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kycprofile",
            name="document_back",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="document_front",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="kycprofile",
            name="selfie_with_doc",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
